server.port: 9000

spring.profiles.active: dev

## logging
logging:
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} [%X{source}] [%X{correlation-id}] [%-5level] [%C:%L] - %m%n'
  file: logs/spanner-pollar-convereter-publisher/app.log
  level.org.springframework: info

# actuator properties
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
  info.git.mode: full

info:
  app:
    name: spanner-pollar-convereter-publisher
    description: Google cloud spanner poller converter publisher
    version: 1.0.0
    java-vendor: ${java.specification.vendor}

---
spring.profiles: dev

---
spring.profiles: test

---
spring.profiles: prod

---
#spring.cloud.gcp.project-id: sacred-garden-307305
#spring.cloud.gcp.credentials.location: file:C:\\Users\\ashu3\\AppData\\Roaming\\gcloud\\application_default_credentials.json
